#!/usr/bin/env bash

cd "${0%/*}/.."
source dotfiles.config
BACKUP_DIR='backup'


if [ ! -d $BACKUP_DIR ]; then
    echo Creating backup directory
    mkdir $BACKUP_DIR
fi

#for f in $(cat $CONFIG); do
echo Backing up dotfiles
for f in ${files[@]}; do
    echo "  $f"
    cp -f ~/$f $BACKUP_DIR/$f
done
